// GENERATED by tools/precompute.mjs — do not edit by hand.
// Versioned seed table: each entry was verified solvable by certificate
// replay and banded by strategy-playout win rate at generation time.
export const SEED_TABLE_VERSION = 1;
export const SEED_TABLE = {
 "sprout": {
  "gentle": [
   {
    "seed": 7,
    "winRate": 0.6,
    "avgSteps": 52
   },
   {
    "seed": 8,
    "winRate": 0.83,
    "avgSteps": 58
   },
   {
    "seed": 21,
    "winRate": 0.67,
    "avgSteps": 57
   },
   {
    "seed": 31,
    "winRate": 0.79,
    "avgSteps": 56
   },
   {
    "seed": 43,
    "winRate": 1,
    "avgSteps": 59
   },
   {
    "seed": 52,
    "winRate": 0.94,
    "avgSteps": 59
   },
   {
    "seed": 54,
    "winRate": 0.81,
    "avgSteps": 61
   },
   {
    "seed": 81,
    "winRate": 0.98,
    "avgSteps": 57
   },
   {
    "seed": 90,
    "winRate": 0.73,
    "avgSteps": 58
   },
   {
    "seed": 109,
    "winRate": 0.67,
    "avgSteps": 57
   },
   {
    "seed": 112,
    "winRate": 0.98,
    "avgSteps": 61
   },
   {
    "seed": 118,
    "winRate": 0.83,
    "avgSteps": 60
   },
   {
    "seed": 125,
    "winRate": 0.9,
    "avgSteps": 57
   },
   {
    "seed": 128,
    "winRate": 0.96,
    "avgSteps": 59
   },
   {
    "seed": 140,
    "winRate": 0.71,
    "avgSteps": 56
   },
   {
    "seed": 150,
    "winRate": 0.65,
    "avgSteps": 54
   },
   {
    "seed": 198,
    "winRate": 0.81,
    "avgSteps": 55
   },
   {
    "seed": 220,
    "winRate": 0.96,
    "avgSteps": 56
   },
   {
    "seed": 229,
    "winRate": 1,
    "avgSteps": 61
   },
   {
    "seed": 230,
    "winRate": 0.9,
    "avgSteps": 55
   },
   {
    "seed": 235,
    "winRate": 0.77,
    "avgSteps": 55
   },
   {
    "seed": 256,
    "winRate": 0.71,
    "avgSteps": 56
   },
   {
    "seed": 272,
    "winRate": 0.67,
    "avgSteps": 56
   },
   {
    "seed": 274,
    "winRate": 0.98,
    "avgSteps": 56
   }
  ],
  "easy": [
   {
    "seed": 4,
    "winRate": 0.46,
    "avgSteps": 34
   },
   {
    "seed": 5,
    "winRate": 0.38,
    "avgSteps": 43
   },
   {
    "seed": 22,
    "winRate": 0.5,
    "avgSteps": 48
   },
   {
    "seed": 49,
    "winRate": 0.42,
    "avgSteps": 47
   },
   {
    "seed": 69,
    "winRate": 0.52,
    "avgSteps": 49
   },
   {
    "seed": 72,
    "winRate": 0.38,
    "avgSteps": 41
   },
   {
    "seed": 87,
    "winRate": 0.44,
    "avgSteps": 41
   },
   {
    "seed": 92,
    "winRate": 0.5,
    "avgSteps": 40
   },
   {
    "seed": 94,
    "winRate": 0.48,
    "avgSteps": 48
   },
   {
    "seed": 97,
    "winRate": 0.44,
    "avgSteps": 44
   },
   {
    "seed": 103,
    "winRate": 0.54,
    "avgSteps": 47
   },
   {
    "seed": 107,
    "winRate": 0.56,
    "avgSteps": 44
   },
   {
    "seed": 121,
    "winRate": 0.5,
    "avgSteps": 54
   },
   {
    "seed": 123,
    "winRate": 0.35,
    "avgSteps": 48
   },
   {
    "seed": 132,
    "winRate": 0.44,
    "avgSteps": 33
   },
   {
    "seed": 134,
    "winRate": 0.35,
    "avgSteps": 43
   },
   {
    "seed": 159,
    "winRate": 0.44,
    "avgSteps": 44
   },
   {
    "seed": 163,
    "winRate": 0.38,
    "avgSteps": 28
   },
   {
    "seed": 170,
    "winRate": 0.58,
    "avgSteps": 45
   },
   {
    "seed": 176,
    "winRate": 0.44,
    "avgSteps": 44
   },
   {
    "seed": 178,
    "winRate": 0.4,
    "avgSteps": 51
   },
   {
    "seed": 196,
    "winRate": 0.4,
    "avgSteps": 54
   },
   {
    "seed": 202,
    "winRate": 0.4,
    "avgSteps": 39
   },
   {
    "seed": 203,
    "winRate": 0.42,
    "avgSteps": 52
   }
  ],
  "medium": [
   {
    "seed": 9,
    "winRate": 0.25,
    "avgSteps": 42
   },
   {
    "seed": 19,
    "winRate": 0.19,
    "avgSteps": 38
   },
   {
    "seed": 20,
    "winRate": 0.31,
    "avgSteps": 37
   },
   {
    "seed": 24,
    "winRate": 0.23,
    "avgSteps": 34
   },
   {
    "seed": 26,
    "winRate": 0.19,
    "avgSteps": 40
   },
   {
    "seed": 29,
    "winRate": 0.25,
    "avgSteps": 35
   },
   {
    "seed": 40,
    "winRate": 0.27,
    "avgSteps": 25
   },
   {
    "seed": 42,
    "winRate": 0.17,
    "avgSteps": 40
   },
   {
    "seed": 47,
    "winRate": 0.17,
    "avgSteps": 35
   },
   {
    "seed": 48,
    "winRate": 0.21,
    "avgSteps": 26
   },
   {
    "seed": 51,
    "winRate": 0.29,
    "avgSteps": 30
   },
   {
    "seed": 53,
    "winRate": 0.17,
    "avgSteps": 27
   },
   {
    "seed": 57,
    "winRate": 0.29,
    "avgSteps": 42
   },
   {
    "seed": 62,
    "winRate": 0.23,
    "avgSteps": 41
   },
   {
    "seed": 70,
    "winRate": 0.25,
    "avgSteps": 42
   },
   {
    "seed": 75,
    "winRate": 0.21,
    "avgSteps": 44
   },
   {
    "seed": 82,
    "winRate": 0.17,
    "avgSteps": 42
   },
   {
    "seed": 86,
    "winRate": 0.25,
    "avgSteps": 28
   },
   {
    "seed": 91,
    "winRate": 0.21,
    "avgSteps": 34
   },
   {
    "seed": 96,
    "winRate": 0.27,
    "avgSteps": 43
   },
   {
    "seed": 98,
    "winRate": 0.19,
    "avgSteps": 37
   },
   {
    "seed": 102,
    "winRate": 0.31,
    "avgSteps": 43
   },
   {
    "seed": 115,
    "winRate": 0.19,
    "avgSteps": 51
   },
   {
    "seed": 117,
    "winRate": 0.29,
    "avgSteps": 35
   }
  ],
  "hard": [
   {
    "seed": 6,
    "winRate": 0.13,
    "avgSteps": 39
   },
   {
    "seed": 12,
    "winRate": 0.08,
    "avgSteps": 24
   },
   {
    "seed": 14,
    "winRate": 0.1,
    "avgSteps": 17
   },
   {
    "seed": 17,
    "winRate": 0.1,
    "avgSteps": 30
   },
   {
    "seed": 28,
    "winRate": 0.06,
    "avgSteps": 34
   },
   {
    "seed": 38,
    "winRate": 0.15,
    "avgSteps": 33
   },
   {
    "seed": 39,
    "winRate": 0.13,
    "avgSteps": 30
   },
   {
    "seed": 41,
    "winRate": 0.15,
    "avgSteps": 36
   },
   {
    "seed": 44,
    "winRate": 0.13,
    "avgSteps": 38
   },
   {
    "seed": 60,
    "winRate": 0.1,
    "avgSteps": 29
   },
   {
    "seed": 61,
    "winRate": 0.06,
    "avgSteps": 16
   },
   {
    "seed": 64,
    "winRate": 0.06,
    "avgSteps": 36
   },
   {
    "seed": 65,
    "winRate": 0.15,
    "avgSteps": 44
   },
   {
    "seed": 68,
    "winRate": 0.15,
    "avgSteps": 28
   },
   {
    "seed": 74,
    "winRate": 0.06,
    "avgSteps": 31
   },
   {
    "seed": 79,
    "winRate": 0.15,
    "avgSteps": 30
   },
   {
    "seed": 83,
    "winRate": 0.13,
    "avgSteps": 22
   },
   {
    "seed": 101,
    "winRate": 0.08,
    "avgSteps": 32
   },
   {
    "seed": 105,
    "winRate": 0.15,
    "avgSteps": 32
   },
   {
    "seed": 113,
    "winRate": 0.06,
    "avgSteps": 27
   },
   {
    "seed": 120,
    "winRate": 0.06,
    "avgSteps": 42
   },
   {
    "seed": 122,
    "winRate": 0.1,
    "avgSteps": 37
   },
   {
    "seed": 130,
    "winRate": 0.15,
    "avgSteps": 29
   },
   {
    "seed": 131,
    "winRate": 0.08,
    "avgSteps": 34
   }
  ],
  "thorny": [
   {
    "seed": 1,
    "winRate": 0,
    "avgSteps": 13
   },
   {
    "seed": 2,
    "winRate": 0.02,
    "avgSteps": 30
   },
   {
    "seed": 3,
    "winRate": 0,
    "avgSteps": 32
   },
   {
    "seed": 10,
    "winRate": 0.04,
    "avgSteps": 36
   },
   {
    "seed": 11,
    "winRate": 0.04,
    "avgSteps": 20
   },
   {
    "seed": 13,
    "winRate": 0,
    "avgSteps": 40
   },
   {
    "seed": 15,
    "winRate": 0.02,
    "avgSteps": 33
   },
   {
    "seed": 16,
    "winRate": 0.02,
    "avgSteps": 25
   },
   {
    "seed": 18,
    "winRate": 0.04,
    "avgSteps": 35
   },
   {
    "seed": 23,
    "winRate": 0.04,
    "avgSteps": 42
   },
   {
    "seed": 25,
    "winRate": 0,
    "avgSteps": 8
   },
   {
    "seed": 27,
    "winRate": 0.04,
    "avgSteps": 13
   },
   {
    "seed": 30,
    "winRate": 0,
    "avgSteps": 6
   },
   {
    "seed": 32,
    "winRate": 0,
    "avgSteps": 15
   },
   {
    "seed": 33,
    "winRate": 0,
    "avgSteps": 27
   },
   {
    "seed": 34,
    "winRate": 0.02,
    "avgSteps": 22
   },
   {
    "seed": 35,
    "winRate": 0,
    "avgSteps": 20
   },
   {
    "seed": 36,
    "winRate": 0,
    "avgSteps": 40
   },
   {
    "seed": 37,
    "winRate": 0,
    "avgSteps": 23
   },
   {
    "seed": 45,
    "winRate": 0,
    "avgSteps": 22
   },
   {
    "seed": 46,
    "winRate": 0.04,
    "avgSteps": 40
   },
   {
    "seed": 50,
    "winRate": 0,
    "avgSteps": 37
   },
   {
    "seed": 55,
    "winRate": 0,
    "avgSteps": 9
   },
   {
    "seed": 56,
    "winRate": 0.02,
    "avgSteps": 27
   }
  ]
 },
 "meadow": {
  "gentle": [
   {
    "seed": 2,
    "winRate": 0.79,
    "avgSteps": 41
   },
   {
    "seed": 13,
    "winRate": 0.67,
    "avgSteps": 48
   },
   {
    "seed": 14,
    "winRate": 0.63,
    "avgSteps": 39
   },
   {
    "seed": 21,
    "winRate": 0.63,
    "avgSteps": 42
   },
   {
    "seed": 27,
    "winRate": 0.85,
    "avgSteps": 48
   },
   {
    "seed": 29,
    "winRate": 0.81,
    "avgSteps": 40
   },
   {
    "seed": 39,
    "winRate": 0.77,
    "avgSteps": 40
   },
   {
    "seed": 56,
    "winRate": 0.67,
    "avgSteps": 48
   },
   {
    "seed": 61,
    "winRate": 0.75,
    "avgSteps": 47
   },
   {
    "seed": 64,
    "winRate": 0.65,
    "avgSteps": 48
   },
   {
    "seed": 65,
    "winRate": 0.71,
    "avgSteps": 40
   },
   {
    "seed": 67,
    "winRate": 0.75,
    "avgSteps": 43
   },
   {
    "seed": 71,
    "winRate": 0.77,
    "avgSteps": 47
   },
   {
    "seed": 76,
    "winRate": 0.75,
    "avgSteps": 43
   },
   {
    "seed": 83,
    "winRate": 0.79,
    "avgSteps": 40
   },
   {
    "seed": 98,
    "winRate": 0.63,
    "avgSteps": 47
   },
   {
    "seed": 100,
    "winRate": 0.73,
    "avgSteps": 40
   },
   {
    "seed": 104,
    "winRate": 0.88,
    "avgSteps": 45
   },
   {
    "seed": 105,
    "winRate": 0.88,
    "avgSteps": 44
   },
   {
    "seed": 116,
    "winRate": 0.83,
    "avgSteps": 44
   },
   {
    "seed": 117,
    "winRate": 0.65,
    "avgSteps": 38
   },
   {
    "seed": 121,
    "winRate": 0.63,
    "avgSteps": 43
   },
   {
    "seed": 125,
    "winRate": 0.71,
    "avgSteps": 42
   },
   {
    "seed": 130,
    "winRate": 0.88,
    "avgSteps": 47
   }
  ],
  "easy": [
   {
    "seed": 20,
    "winRate": 0.44,
    "avgSteps": 41
   },
   {
    "seed": 26,
    "winRate": 0.56,
    "avgSteps": 35
   },
   {
    "seed": 40,
    "winRate": 0.58,
    "avgSteps": 40
   },
   {
    "seed": 42,
    "winRate": 0.38,
    "avgSteps": 31
   },
   {
    "seed": 46,
    "winRate": 0.46,
    "avgSteps": 33
   },
   {
    "seed": 47,
    "winRate": 0.5,
    "avgSteps": 29
   },
   {
    "seed": 51,
    "winRate": 0.35,
    "avgSteps": 31
   },
   {
    "seed": 66,
    "winRate": 0.56,
    "avgSteps": 34
   },
   {
    "seed": 77,
    "winRate": 0.48,
    "avgSteps": 43
   },
   {
    "seed": 78,
    "winRate": 0.58,
    "avgSteps": 41
   },
   {
    "seed": 87,
    "winRate": 0.4,
    "avgSteps": 40
   },
   {
    "seed": 99,
    "winRate": 0.46,
    "avgSteps": 36
   },
   {
    "seed": 106,
    "winRate": 0.38,
    "avgSteps": 36
   },
   {
    "seed": 127,
    "winRate": 0.38,
    "avgSteps": 35
   },
   {
    "seed": 162,
    "winRate": 0.48,
    "avgSteps": 41
   },
   {
    "seed": 164,
    "winRate": 0.35,
    "avgSteps": 33
   },
   {
    "seed": 174,
    "winRate": 0.48,
    "avgSteps": 42
   },
   {
    "seed": 187,
    "winRate": 0.44,
    "avgSteps": 35
   },
   {
    "seed": 207,
    "winRate": 0.44,
    "avgSteps": 35
   },
   {
    "seed": 222,
    "winRate": 0.48,
    "avgSteps": 34
   },
   {
    "seed": 228,
    "winRate": 0.56,
    "avgSteps": 41
   },
   {
    "seed": 230,
    "winRate": 0.38,
    "avgSteps": 36
   },
   {
    "seed": 232,
    "winRate": 0.35,
    "avgSteps": 32
   },
   {
    "seed": 241,
    "winRate": 0.5,
    "avgSteps": 42
   }
  ],
  "medium": [
   {
    "seed": 5,
    "winRate": 0.25,
    "avgSteps": 32
   },
   {
    "seed": 7,
    "winRate": 0.29,
    "avgSteps": 33
   },
   {
    "seed": 9,
    "winRate": 0.31,
    "avgSteps": 41
   },
   {
    "seed": 17,
    "winRate": 0.19,
    "avgSteps": 24
   },
   {
    "seed": 18,
    "winRate": 0.17,
    "avgSteps": 20
   },
   {
    "seed": 22,
    "winRate": 0.31,
    "avgSteps": 32
   },
   {
    "seed": 24,
    "winRate": 0.19,
    "avgSteps": 24
   },
   {
    "seed": 25,
    "winRate": 0.23,
    "avgSteps": 23
   },
   {
    "seed": 41,
    "winRate": 0.17,
    "avgSteps": 35
   },
   {
    "seed": 55,
    "winRate": 0.31,
    "avgSteps": 42
   },
   {
    "seed": 62,
    "winRate": 0.19,
    "avgSteps": 33
   },
   {
    "seed": 63,
    "winRate": 0.23,
    "avgSteps": 26
   },
   {
    "seed": 73,
    "winRate": 0.23,
    "avgSteps": 28
   },
   {
    "seed": 80,
    "winRate": 0.25,
    "avgSteps": 30
   },
   {
    "seed": 86,
    "winRate": 0.31,
    "avgSteps": 28
   },
   {
    "seed": 90,
    "winRate": 0.17,
    "avgSteps": 35
   },
   {
    "seed": 96,
    "winRate": 0.33,
    "avgSteps": 22
   },
   {
    "seed": 97,
    "winRate": 0.19,
    "avgSteps": 21
   },
   {
    "seed": 101,
    "winRate": 0.29,
    "avgSteps": 27
   },
   {
    "seed": 126,
    "winRate": 0.19,
    "avgSteps": 18
   },
   {
    "seed": 133,
    "winRate": 0.17,
    "avgSteps": 31
   },
   {
    "seed": 136,
    "winRate": 0.17,
    "avgSteps": 34
   },
   {
    "seed": 137,
    "winRate": 0.33,
    "avgSteps": 29
   },
   {
    "seed": 141,
    "winRate": 0.21,
    "avgSteps": 22
   }
  ],
  "hard": [
   {
    "seed": 4,
    "winRate": 0.1,
    "avgSteps": 20
   },
   {
    "seed": 10,
    "winRate": 0.13,
    "avgSteps": 26
   },
   {
    "seed": 28,
    "winRate": 0.08,
    "avgSteps": 18
   },
   {
    "seed": 31,
    "winRate": 0.06,
    "avgSteps": 19
   },
   {
    "seed": 34,
    "winRate": 0.08,
    "avgSteps": 19
   },
   {
    "seed": 43,
    "winRate": 0.08,
    "avgSteps": 26
   },
   {
    "seed": 44,
    "winRate": 0.15,
    "avgSteps": 27
   },
   {
    "seed": 45,
    "winRate": 0.13,
    "avgSteps": 30
   },
   {
    "seed": 48,
    "winRate": 0.15,
    "avgSteps": 20
   },
   {
    "seed": 59,
    "winRate": 0.15,
    "avgSteps": 26
   },
   {
    "seed": 69,
    "winRate": 0.13,
    "avgSteps": 33
   },
   {
    "seed": 84,
    "winRate": 0.1,
    "avgSteps": 18
   },
   {
    "seed": 85,
    "winRate": 0.1,
    "avgSteps": 32
   },
   {
    "seed": 102,
    "winRate": 0.1,
    "avgSteps": 24
   },
   {
    "seed": 111,
    "winRate": 0.06,
    "avgSteps": 18
   },
   {
    "seed": 161,
    "winRate": 0.13,
    "avgSteps": 18
   },
   {
    "seed": 163,
    "winRate": 0.08,
    "avgSteps": 22
   },
   {
    "seed": 176,
    "winRate": 0.13,
    "avgSteps": 28
   },
   {
    "seed": 204,
    "winRate": 0.1,
    "avgSteps": 23
   },
   {
    "seed": 208,
    "winRate": 0.08,
    "avgSteps": 22
   },
   {
    "seed": 219,
    "winRate": 0.06,
    "avgSteps": 23
   },
   {
    "seed": 234,
    "winRate": 0.08,
    "avgSteps": 19
   },
   {
    "seed": 238,
    "winRate": 0.15,
    "avgSteps": 23
   },
   {
    "seed": 247,
    "winRate": 0.06,
    "avgSteps": 24
   }
  ],
  "thorny": [
   {
    "seed": 1,
    "winRate": 0,
    "avgSteps": 13
   },
   {
    "seed": 3,
    "winRate": 0,
    "avgSteps": 6
   },
   {
    "seed": 6,
    "winRate": 0.02,
    "avgSteps": 19
   },
   {
    "seed": 8,
    "winRate": 0,
    "avgSteps": 4
   },
   {
    "seed": 11,
    "winRate": 0,
    "avgSteps": 7
   },
   {
    "seed": 12,
    "winRate": 0,
    "avgSteps": 15
   },
   {
    "seed": 15,
    "winRate": 0,
    "avgSteps": 8
   },
   {
    "seed": 16,
    "winRate": 0,
    "avgSteps": 5
   },
   {
    "seed": 19,
    "winRate": 0,
    "avgSteps": 16
   },
   {
    "seed": 23,
    "winRate": 0,
    "avgSteps": 16
   },
   {
    "seed": 30,
    "winRate": 0,
    "avgSteps": 19
   },
   {
    "seed": 32,
    "winRate": 0,
    "avgSteps": 11
   },
   {
    "seed": 33,
    "winRate": 0,
    "avgSteps": 12
   },
   {
    "seed": 35,
    "winRate": 0,
    "avgSteps": 20
   },
   {
    "seed": 36,
    "winRate": 0,
    "avgSteps": 16
   },
   {
    "seed": 37,
    "winRate": 0.02,
    "avgSteps": 20
   },
   {
    "seed": 38,
    "winRate": 0,
    "avgSteps": 12
   },
   {
    "seed": 49,
    "winRate": 0,
    "avgSteps": 23
   },
   {
    "seed": 50,
    "winRate": 0,
    "avgSteps": 18
   },
   {
    "seed": 52,
    "winRate": 0,
    "avgSteps": 6
   },
   {
    "seed": 53,
    "winRate": 0,
    "avgSteps": 24
   },
   {
    "seed": 54,
    "winRate": 0,
    "avgSteps": 9
   },
   {
    "seed": 57,
    "winRate": 0,
    "avgSteps": 17
   },
   {
    "seed": 58,
    "winRate": 0,
    "avgSteps": 5
   }
  ]
 },
 "thicket": {
  "gentle": [
   {
    "seed": 153,
    "winRate": 0.92,
    "avgSteps": 58
   },
   {
    "seed": 342,
    "winRate": 0.67,
    "avgSteps": 58
   },
   {
    "seed": 360,
    "winRate": 0.63,
    "avgSteps": 48
   }
  ],
  "easy": [
   {
    "seed": 57,
    "winRate": 0.38,
    "avgSteps": 51
   },
   {
    "seed": 102,
    "winRate": 0.4,
    "avgSteps": 46
   },
   {
    "seed": 166,
    "winRate": 0.54,
    "avgSteps": 57
   },
   {
    "seed": 235,
    "winRate": 0.5,
    "avgSteps": 51
   },
   {
    "seed": 249,
    "winRate": 0.54,
    "avgSteps": 44
   },
   {
    "seed": 286,
    "winRate": 0.38,
    "avgSteps": 49
   },
   {
    "seed": 395,
    "winRate": 0.58,
    "avgSteps": 46
   },
   {
    "seed": 402,
    "winRate": 0.44,
    "avgSteps": 45
   }
  ],
  "medium": [
   {
    "seed": 46,
    "winRate": 0.17,
    "avgSteps": 40
   },
   {
    "seed": 52,
    "winRate": 0.23,
    "avgSteps": 52
   },
   {
    "seed": 66,
    "winRate": 0.27,
    "avgSteps": 34
   },
   {
    "seed": 93,
    "winRate": 0.19,
    "avgSteps": 50
   },
   {
    "seed": 111,
    "winRate": 0.27,
    "avgSteps": 38
   },
   {
    "seed": 122,
    "winRate": 0.23,
    "avgSteps": 42
   },
   {
    "seed": 130,
    "winRate": 0.17,
    "avgSteps": 35
   },
   {
    "seed": 161,
    "winRate": 0.27,
    "avgSteps": 49
   },
   {
    "seed": 162,
    "winRate": 0.29,
    "avgSteps": 27
   },
   {
    "seed": 190,
    "winRate": 0.17,
    "avgSteps": 29
   },
   {
    "seed": 208,
    "winRate": 0.25,
    "avgSteps": 45
   },
   {
    "seed": 221,
    "winRate": 0.33,
    "avgSteps": 32
   },
   {
    "seed": 263,
    "winRate": 0.19,
    "avgSteps": 37
   },
   {
    "seed": 291,
    "winRate": 0.21,
    "avgSteps": 26
   },
   {
    "seed": 321,
    "winRate": 0.25,
    "avgSteps": 39
   },
   {
    "seed": 326,
    "winRate": 0.17,
    "avgSteps": 39
   },
   {
    "seed": 366,
    "winRate": 0.17,
    "avgSteps": 48
   },
   {
    "seed": 386,
    "winRate": 0.31,
    "avgSteps": 40
   },
   {
    "seed": 391,
    "winRate": 0.19,
    "avgSteps": 34
   },
   {
    "seed": 404,
    "winRate": 0.17,
    "avgSteps": 50
   },
   {
    "seed": 407,
    "winRate": 0.25,
    "avgSteps": 44
   },
   {
    "seed": 413,
    "winRate": 0.21,
    "avgSteps": 35
   },
   {
    "seed": 423,
    "winRate": 0.31,
    "avgSteps": 49
   },
   {
    "seed": 437,
    "winRate": 0.25,
    "avgSteps": 45
   }
  ],
  "hard": [
   {
    "seed": 3,
    "winRate": 0.08,
    "avgSteps": 41
   },
   {
    "seed": 12,
    "winRate": 0.06,
    "avgSteps": 28
   },
   {
    "seed": 21,
    "winRate": 0.15,
    "avgSteps": 23
   },
   {
    "seed": 36,
    "winRate": 0.06,
    "avgSteps": 25
   },
   {
    "seed": 39,
    "winRate": 0.13,
    "avgSteps": 43
   },
   {
    "seed": 45,
    "winRate": 0.06,
    "avgSteps": 17
   },
   {
    "seed": 51,
    "winRate": 0.06,
    "avgSteps": 19
   },
   {
    "seed": 53,
    "winRate": 0.06,
    "avgSteps": 31
   },
   {
    "seed": 67,
    "winRate": 0.06,
    "avgSteps": 36
   },
   {
    "seed": 68,
    "winRate": 0.06,
    "avgSteps": 36
   },
   {
    "seed": 69,
    "winRate": 0.15,
    "avgSteps": 40
   },
   {
    "seed": 76,
    "winRate": 0.08,
    "avgSteps": 21
   },
   {
    "seed": 86,
    "winRate": 0.06,
    "avgSteps": 31
   },
   {
    "seed": 87,
    "winRate": 0.06,
    "avgSteps": 49
   },
   {
    "seed": 98,
    "winRate": 0.06,
    "avgSteps": 34
   },
   {
    "seed": 103,
    "winRate": 0.06,
    "avgSteps": 40
   },
   {
    "seed": 107,
    "winRate": 0.08,
    "avgSteps": 27
   },
   {
    "seed": 119,
    "winRate": 0.15,
    "avgSteps": 39
   },
   {
    "seed": 126,
    "winRate": 0.13,
    "avgSteps": 33
   },
   {
    "seed": 127,
    "winRate": 0.1,
    "avgSteps": 30
   },
   {
    "seed": 133,
    "winRate": 0.06,
    "avgSteps": 43
   },
   {
    "seed": 151,
    "winRate": 0.08,
    "avgSteps": 35
   },
   {
    "seed": 164,
    "winRate": 0.08,
    "avgSteps": 27
   },
   {
    "seed": 179,
    "winRate": 0.1,
    "avgSteps": 37
   }
  ],
  "thorny": [
   {
    "seed": 1,
    "winRate": 0.02,
    "avgSteps": 22
   },
   {
    "seed": 2,
    "winRate": 0,
    "avgSteps": 24
   },
   {
    "seed": 4,
    "winRate": 0,
    "avgSteps": 32
   },
   {
    "seed": 5,
    "winRate": 0,
    "avgSteps": 6
   },
   {
    "seed": 6,
    "winRate": 0,
    "avgSteps": 6
   },
   {
    "seed": 7,
    "winRate": 0,
    "avgSteps": 7
   },
   {
    "seed": 8,
    "winRate": 0,
    "avgSteps": 44
   },
   {
    "seed": 9,
    "winRate": 0,
    "avgSteps": 27
   },
   {
    "seed": 10,
    "winRate": 0,
    "avgSteps": 18
   },
   {
    "seed": 11,
    "winRate": 0,
    "avgSteps": 8
   },
   {
    "seed": 13,
    "winRate": 0,
    "avgSteps": 34
   },
   {
    "seed": 14,
    "winRate": 0,
    "avgSteps": 21
   },
   {
    "seed": 15,
    "winRate": 0,
    "avgSteps": 7
   },
   {
    "seed": 16,
    "winRate": 0,
    "avgSteps": 42
   },
   {
    "seed": 17,
    "winRate": 0,
    "avgSteps": 32
   },
   {
    "seed": 18,
    "winRate": 0,
    "avgSteps": 16
   },
   {
    "seed": 19,
    "winRate": 0,
    "avgSteps": 28
   },
   {
    "seed": 20,
    "winRate": 0,
    "avgSteps": 7
   },
   {
    "seed": 22,
    "winRate": 0,
    "avgSteps": 6
   },
   {
    "seed": 23,
    "winRate": 0,
    "avgSteps": 7
   },
   {
    "seed": 24,
    "winRate": 0,
    "avgSteps": 12
   },
   {
    "seed": 25,
    "winRate": 0.02,
    "avgSteps": 26
   },
   {
    "seed": 26,
    "winRate": 0,
    "avgSteps": 8
   },
   {
    "seed": 27,
    "winRate": 0,
    "avgSteps": 38
   }
  ]
 },
 "wildwood": {
  "gentle": [
   {
    "seed": 101,
    "winRate": 1,
    "avgSteps": 40
   },
   {
    "seed": 120,
    "winRate": 0.65,
    "avgSteps": 49
   },
   {
    "seed": 426,
    "winRate": 0.69,
    "avgSteps": 44
   }
  ],
  "easy": [
   {
    "seed": 40,
    "winRate": 0.46,
    "avgSteps": 42
   },
   {
    "seed": 194,
    "winRate": 0.56,
    "avgSteps": 36
   },
   {
    "seed": 211,
    "winRate": 0.48,
    "avgSteps": 44
   },
   {
    "seed": 233,
    "winRate": 0.48,
    "avgSteps": 41
   },
   {
    "seed": 262,
    "winRate": 0.4,
    "avgSteps": 39
   },
   {
    "seed": 265,
    "winRate": 0.5,
    "avgSteps": 41
   },
   {
    "seed": 273,
    "winRate": 0.42,
    "avgSteps": 38
   },
   {
    "seed": 382,
    "winRate": 0.56,
    "avgSteps": 45
   },
   {
    "seed": 413,
    "winRate": 0.42,
    "avgSteps": 37
   },
   {
    "seed": 460,
    "winRate": 0.44,
    "avgSteps": 39
   },
   {
    "seed": 471,
    "winRate": 0.4,
    "avgSteps": 35
   }
  ],
  "medium": [
   {
    "seed": 12,
    "winRate": 0.21,
    "avgSteps": 18
   },
   {
    "seed": 24,
    "winRate": 0.33,
    "avgSteps": 38
   },
   {
    "seed": 71,
    "winRate": 0.21,
    "avgSteps": 46
   },
   {
    "seed": 112,
    "winRate": 0.27,
    "avgSteps": 41
   },
   {
    "seed": 117,
    "winRate": 0.19,
    "avgSteps": 39
   },
   {
    "seed": 123,
    "winRate": 0.17,
    "avgSteps": 26
   },
   {
    "seed": 136,
    "winRate": 0.25,
    "avgSteps": 36
   },
   {
    "seed": 141,
    "winRate": 0.29,
    "avgSteps": 36
   },
   {
    "seed": 192,
    "winRate": 0.19,
    "avgSteps": 26
   },
   {
    "seed": 206,
    "winRate": 0.19,
    "avgSteps": 32
   },
   {
    "seed": 236,
    "winRate": 0.31,
    "avgSteps": 32
   },
   {
    "seed": 242,
    "winRate": 0.21,
    "avgSteps": 41
   },
   {
    "seed": 248,
    "winRate": 0.19,
    "avgSteps": 33
   },
   {
    "seed": 259,
    "winRate": 0.19,
    "avgSteps": 36
   },
   {
    "seed": 278,
    "winRate": 0.29,
    "avgSteps": 35
   },
   {
    "seed": 288,
    "winRate": 0.21,
    "avgSteps": 33
   },
   {
    "seed": 290,
    "winRate": 0.29,
    "avgSteps": 28
   },
   {
    "seed": 291,
    "winRate": 0.21,
    "avgSteps": 38
   },
   {
    "seed": 310,
    "winRate": 0.21,
    "avgSteps": 26
   },
   {
    "seed": 355,
    "winRate": 0.33,
    "avgSteps": 46
   },
   {
    "seed": 360,
    "winRate": 0.25,
    "avgSteps": 23
   },
   {
    "seed": 389,
    "winRate": 0.27,
    "avgSteps": 39
   },
   {
    "seed": 395,
    "winRate": 0.21,
    "avgSteps": 39
   },
   {
    "seed": 404,
    "winRate": 0.21,
    "avgSteps": 22
   }
  ],
  "hard": [
   {
    "seed": 1,
    "winRate": 0.06,
    "avgSteps": 28
   },
   {
    "seed": 4,
    "winRate": 0.06,
    "avgSteps": 37
   },
   {
    "seed": 9,
    "winRate": 0.08,
    "avgSteps": 30
   },
   {
    "seed": 21,
    "winRate": 0.06,
    "avgSteps": 25
   },
   {
    "seed": 27,
    "winRate": 0.15,
    "avgSteps": 25
   },
   {
    "seed": 28,
    "winRate": 0.08,
    "avgSteps": 38
   },
   {
    "seed": 29,
    "winRate": 0.1,
    "avgSteps": 39
   },
   {
    "seed": 35,
    "winRate": 0.1,
    "avgSteps": 30
   },
   {
    "seed": 46,
    "winRate": 0.06,
    "avgSteps": 23
   },
   {
    "seed": 47,
    "winRate": 0.1,
    "avgSteps": 28
   },
   {
    "seed": 52,
    "winRate": 0.06,
    "avgSteps": 34
   },
   {
    "seed": 67,
    "winRate": 0.13,
    "avgSteps": 27
   },
   {
    "seed": 79,
    "winRate": 0.06,
    "avgSteps": 31
   },
   {
    "seed": 88,
    "winRate": 0.15,
    "avgSteps": 31
   },
   {
    "seed": 89,
    "winRate": 0.15,
    "avgSteps": 37
   },
   {
    "seed": 96,
    "winRate": 0.15,
    "avgSteps": 39
   },
   {
    "seed": 102,
    "winRate": 0.06,
    "avgSteps": 22
   },
   {
    "seed": 103,
    "winRate": 0.08,
    "avgSteps": 28
   },
   {
    "seed": 107,
    "winRate": 0.06,
    "avgSteps": 25
   },
   {
    "seed": 108,
    "winRate": 0.13,
    "avgSteps": 38
   },
   {
    "seed": 110,
    "winRate": 0.1,
    "avgSteps": 31
   },
   {
    "seed": 111,
    "winRate": 0.13,
    "avgSteps": 35
   },
   {
    "seed": 126,
    "winRate": 0.06,
    "avgSteps": 35
   },
   {
    "seed": 127,
    "winRate": 0.08,
    "avgSteps": 37
   }
  ],
  "thorny": [
   {
    "seed": 2,
    "winRate": 0,
    "avgSteps": 41
   },
   {
    "seed": 3,
    "winRate": 0,
    "avgSteps": 17
   },
   {
    "seed": 5,
    "winRate": 0.02,
    "avgSteps": 30
   },
   {
    "seed": 6,
    "winRate": 0,
    "avgSteps": 34
   },
   {
    "seed": 7,
    "winRate": 0,
    "avgSteps": 5
   },
   {
    "seed": 8,
    "winRate": 0.02,
    "avgSteps": 32
   },
   {
    "seed": 10,
    "winRate": 0,
    "avgSteps": 13
   },
   {
    "seed": 11,
    "winRate": 0.02,
    "avgSteps": 28
   },
   {
    "seed": 13,
    "winRate": 0,
    "avgSteps": 7
   },
   {
    "seed": 14,
    "winRate": 0,
    "avgSteps": 36
   },
   {
    "seed": 15,
    "winRate": 0.04,
    "avgSteps": 27
   },
   {
    "seed": 16,
    "winRate": 0,
    "avgSteps": 22
   },
   {
    "seed": 17,
    "winRate": 0,
    "avgSteps": 25
   },
   {
    "seed": 18,
    "winRate": 0.04,
    "avgSteps": 23
   },
   {
    "seed": 19,
    "winRate": 0,
    "avgSteps": 19
   },
   {
    "seed": 20,
    "winRate": 0,
    "avgSteps": 7
   },
   {
    "seed": 22,
    "winRate": 0,
    "avgSteps": 25
   },
   {
    "seed": 23,
    "winRate": 0,
    "avgSteps": 25
   },
   {
    "seed": 25,
    "winRate": 0,
    "avgSteps": 19
   },
   {
    "seed": 26,
    "winRate": 0.02,
    "avgSteps": 19
   },
   {
    "seed": 30,
    "winRate": 0,
    "avgSteps": 22
   },
   {
    "seed": 31,
    "winRate": 0,
    "avgSteps": 6
   },
   {
    "seed": 32,
    "winRate": 0,
    "avgSteps": 36
   },
   {
    "seed": 33,
    "winRate": 0,
    "avgSteps": 23
   }
  ]
 }
};
