// Offline content preparation for Patience Garden.
// Scans seeds per construction profile, measures approachability with the
// shared playout metric, and emits js/content-seeds.js — a versioned seed
// table the game uses to serve difficulty-banded, guaranteed-solvable deals.
// Run: node tools/precompute.mjs

import { writeFileSync } from 'node:fs';
import { createWinnableGame, generateWinnableLayout, verifyCertificate, estimateWinRate } from '../js/solver.js';

const PROFILES = {
  sprout:   { suitCount: 3, targets: [1, 1, 2, 2, 3, 3, 4] },
  meadow:   { suitCount: 3, targets: [1, 2, 3, 4, 5, 6, 7] },
  thicket:  { suitCount: 4, targets: [1, 1, 2, 2, 3, 4, 5] },
  wildwood: { suitCount: 4, targets: [1, 2, 3, 4, 5, 6, 7] },
};

const BANDS = [
  ['gentle', (r) => r >= 0.60],
  ['easy', (r) => r >= 0.35 && r < 0.60],
  ['medium', (r) => r >= 0.15 && r < 0.35],
  ['hard', (r) => r >= 0.05 && r < 0.15],
  ['thorny', (r) => r < 0.05],
];

const SCAN = 500;        // seeds scanned per profile
const SAMPLES = 48;      // playouts per seed
const KEEP = 24;         // seeds kept per band

const table = {};
const t0 = Date.now();
for (const [name, profile] of Object.entries(PROFILES)) {
  const bands = Object.fromEntries(BANDS.map(([b]) => [b, []]));
  for (let seed = 1; seed <= SCAN; seed++) {
    const { layout, certificate } = generateWinnableLayout(seed, profile);
    const v = verifyCertificate(layout, profile, certificate);
    if (!v.ok) throw new Error(`certificate failed for ${name} seed ${seed}: ${v.error}`);
    const game = createWinnableGame(seed, profile);
    const { winRate, avgSteps } = estimateWinRate(game, SAMPLES, seed);
    const band = BANDS.find(([, test]) => test(winRate))[0];
    if (bands[band].length < KEEP) {
      bands[band].push({ seed, winRate: Math.round(winRate * 100) / 100, avgSteps: Math.round(avgSteps) });
    }
    if (Object.values(bands).every((list) => list.length >= KEEP)) break;
  }
  table[name] = bands;
  const counts = Object.entries(bands).map(([b, l]) => `${b}:${l.length}`).join(' ');
  console.log(name, counts, `(${((Date.now() - t0) / 1000).toFixed(0)}s)`);
}

const out = `// GENERATED by tools/precompute.mjs — do not edit by hand.
// Versioned seed table: each entry was verified solvable by certificate
// replay and banded by strategy-playout win rate at generation time.
export const SEED_TABLE_VERSION = 1;
export const SEED_TABLE = ${JSON.stringify(table, null, 1)};
`;
writeFileSync(new URL('../js/content-seeds.js', import.meta.url), out);
console.log('wrote js/content-seeds.js');
